import { CANONICAL_LAYER_DEFINITIONS } from "@seekstar/core-schema";
import type { Backlink, ExplorationTab, TerrainLayer, TerrainScene } from "@seekstar/core-schema";
import type { DomainLexicon } from "./domainLexicon.js";

let seedSceneCounter = 0;

export interface SeedSceneOptions {
  domainLexicon?: DomainLexicon;
  parentBacklink?: Backlink;
  sceneId?: string;
  sourceMode?: ExplorationTab["source_mode"];
  tabId?: string;
  timestamp?: string;
}

export function createSeedScene(seedText: string, options: SeedSceneOptions = {}): TerrainScene {
  seedSceneCounter += 1;

  const seed = seedText.trim() || "Untitled exploration";
  const slug = toSlug(seed);
  const createdAt = options.timestamp ?? new Date().toISOString();
  const stamp = `${Date.now()}-${seedSceneCounter}`;
  const sceneId = options.sceneId ?? `scene-${slug}-${stamp}`;
  const tabId = options.tabId ?? `tab-${slug}-${stamp}`;

  return {
    id: sceneId,
    active_tab_id: tabId,
    tabs: [
      {
        id: tabId,
        title: seed,
        seed,
        source_mode: options.sourceMode ?? "new_seed",
        parent_backlink: options.parentBacklink,
        current_layer: "L0",
        viewport: { x: 0, y: 0, zoom: 1, layer: "L0" },
        node_ids: [],
        relation_ids: [],
        source_ids: [],
        created_at: createdAt,
        updated_at: createdAt,
      },
    ],
    layers: createCanonicalSeedLayers(seed),
    nodes: [],
    relations: [],
    sources: [],
    viewport: { x: 0, y: 0, zoom: 1, layer: "L0" },
    selection: {
      id: `selection-${slug}-${stamp}`,
      tab_id: tabId,
      node_ids: [],
      source_ids: [],
      text_ranges: [],
      created_at: createdAt,
    },
    agent_jobs: [],
    cartographer_outputs: [],
    scout_observations: [],
    runtime: {
      focused_node_id: undefined,
      browser_absorption: {
        status: "idle",
        exit_layer: "L3",
      },
      updated_at: createdAt,
    },
    metadata: {
      title: seed,
      description: `SeekStar exploration container for "${seed}". Visible terrain is generated by AI Cartographer or backed by real source intake.`,
      source_state: "local_only",
      generated_by: "user",
      created_at: createdAt,
      updated_at: createdAt,
    },
  };
}

function createCanonicalSeedLayers(seed: string): TerrainLayer[] {
  const definitions = CANONICAL_LAYER_DEFINITIONS;

  return definitions.map((definition, index) => ({
    id: definition.id,
    label: definition.label,
    parent_layer_id: index > 0 ? definitions[index - 1].id : undefined,
    child_layer_ids: definitions[index + 1] ? [definitions[index + 1].id] : [],
    breadcrumb: [seed, ...definitions.slice(0, index + 1).map((candidate) => candidate.label)],
  }));
}

function toSlug(value: string): string {
  const slug = value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return slug || "seed";
}
